version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: webscraper-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: web_scraper_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./Server/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - webscraper-network

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: webscraper-server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/web_scraper_db?authSource=admin
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4}
      MAX_FILE_SIZE: 100MB
      UPLOAD_PATH: ./uploads
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      SCREENSHOT_QUALITY: 80
      SCREENSHOT_FORMAT: png
      LOG_LEVEL: info
      LOG_FILE: ./logs/app.log
    ports:
      - "5000:5000"
    volumes:
      - ./Server/uploads:/app/uploads
      - ./Server/logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - webscraper-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: webscraper-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - webscraper-network

  nginx:
    image: nginx:alpine
    container_name: webscraper-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - server
      - client
    networks:
      - webscraper-network

volumes:
  mongodb_data:
    driver: local

networks:
  webscraper-network:
    driver: bridge